-- MySQL Script generated by MySQL Workbench
-- Fri 25 Aug 2017 07:22:43 PM EEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oauth_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oauth_db` DEFAULT CHARACTER SET utf8 ;
USE `oauth_db` ;

-- -----------------------------------------------------
-- Table `oauth_db`.`clientdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`clientdetails` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`clientdetails` (
  `appId` VARCHAR(255) NOT NULL,
  `resourceIds` VARCHAR(255) NULL DEFAULT NULL,
  `appSecret` VARCHAR(255) NULL DEFAULT NULL,
  `scope` VARCHAR(255) NULL DEFAULT NULL,
  `grantTypes` VARCHAR(255) NULL DEFAULT NULL,
  `redirectUrl` VARCHAR(255) NULL DEFAULT NULL,
  `authorities` VARCHAR(255) NULL DEFAULT NULL,
  `access_token_validity` INT(11) NULL DEFAULT NULL,
  `refresh_token_validity` INT(11) NULL DEFAULT NULL,
  `additionalInformation` VARCHAR(4096) NULL DEFAULT NULL,
  `autoApproveScopes` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`appId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`oauth_access_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`oauth_access_token` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`oauth_access_token` (
  `token_id` VARCHAR(255) NULL DEFAULT NULL,
  `token` MEDIUMBLOB NULL DEFAULT NULL,
  `authentication_id` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  `client_id` VARCHAR(255) NULL DEFAULT NULL,
  `authentication` MEDIUMBLOB NULL DEFAULT NULL,
  `refresh_token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`authentication_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`oauth_approvals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`oauth_approvals` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`oauth_approvals` (
  `userId` VARCHAR(255) NULL DEFAULT NULL,
  `clientId` VARCHAR(255) NULL DEFAULT NULL,
  `scope` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `expiresAt` TIMESTAMP NULL DEFAULT NULL,
  `lastModifiedAt` TIMESTAMP NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`oauth_client_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`oauth_client_details` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`oauth_client_details` (
  `client_id` VARCHAR(255) NOT NULL,
  `resource_ids` VARCHAR(255) NULL DEFAULT NULL,
  `client_secret` VARCHAR(255) NULL DEFAULT NULL,
  `scope` VARCHAR(255) NULL DEFAULT NULL,
  `authorized_grant_types` VARCHAR(255) NULL DEFAULT NULL,
  `web_server_redirect_uri` VARCHAR(255) NULL DEFAULT NULL,
  `authorities` VARCHAR(255) NULL DEFAULT NULL,
  `access_token_validity` INT(11) NULL DEFAULT NULL,
  `refresh_token_validity` INT(11) NULL DEFAULT NULL,
  `additional_information` VARCHAR(4096) NULL DEFAULT NULL,
  `autoapprove` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`oauth_client_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`oauth_client_token` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`oauth_client_token` (
  `token_id` VARCHAR(255) NULL DEFAULT NULL,
  `token` MEDIUMBLOB NULL DEFAULT NULL,
  `authentication_id` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  `client_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`authentication_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`oauth_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`oauth_code` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`oauth_code` (
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `authentication` MEDIUMBLOB NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`oauth_refresh_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`oauth_refresh_token` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`oauth_refresh_token` (
  `token_id` VARCHAR(255) NULL DEFAULT NULL,
  `token` MEDIUMBLOB NULL DEFAULT NULL,
  `authentication` MEDIUMBLOB NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`users` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(4) NOT NULL DEFAULT '1',
  `account_non_expired` TINYINT(4) NOT NULL DEFAULT '1',
  `account_non_locked` TINYINT(4) NOT NULL DEFAULT '1',
  `credentials_non_expired` TINYINT(4) NOT NULL DEFAULT '1',
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`user_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`user_attempts` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`user_attempts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `attempts` VARCHAR(45) NOT NULL,
  `last_modified` DATETIME NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_attempts_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_attempts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `oauth_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`user_roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX `uni_username_role` (`role` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_user_roles_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `oauth_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oauth_db`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`groups` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`groups` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `group_name_UNIQUE` (`group_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth_db`.`group_authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`group_authorities` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`group_authorities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(50) NOT NULL,
  `groups_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_authorities_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_group_authorities_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `oauth_db`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth_db`.`group_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`group_members` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`group_members` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `groups_id` BIGINT UNSIGNED NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_members_groups1_idx` (`groups_id` ASC),
  INDEX `fk_group_members_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_group_members_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `oauth_db`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_members_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `oauth_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth_db`.`user_authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oauth_db`.`user_authorities` ;

CREATE TABLE IF NOT EXISTS `oauth_db`.`user_authorities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(50) NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_authorities_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_authorities_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `oauth_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
